services:
  db:
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - file_upload/.env

  redis:
    image: redis:7-alpine
    depends_on:
      - db

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      sh -c "python manage.py makemigrations api &&
      python manage.py migrate api &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - file_upload/.env
    depends_on:
      - db
      - redis
    volumes:
      - media_volume:/usr/src/app/media/

  celery_worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A file_upload worker -l info
    env_file:
      - file_upload/.env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
  media_volume: