# Generated by Django 4.2.10 on 2024-02-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='mdeia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf, png, txt'])], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('processed', models.BooleanField(default=False, verbose_name='Статус проверки')),
            ],
        ),
    ]
